### ISSUE TITLE
fancymenu not working when adding konkrete to the mod that im making, anybody kow why or how to fix? Log below

### ISSUE THREAD

**Issue by Playaspect** [Keksuccino/FancyMenu-Dev-Docs#1]
[debug.log](https://github.com/user-attachments/files/16490609/debug.log)

**Comment by Keksuccino** [comment]
It fails to apply Konkrete's mixins.
You probably made a mistake when adding Konkrete as Gradle dependency. It doesn't correctly remap the JAR.

For future questions, please join the Discord: https://discord.com/invite/UzmeWkD
